version: "3.9"

services:
  php:
    build: docker/php
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=api

  adminer:
    image: "adminer:latest"
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_USERNAME=root
      - ADMINER_PASSWORD=root
      - ADMINER_DB=api
